@extends('frontend.main_master')
@section('main')
    @include('frontend.home.home_banner_area')
    @include('frontend.home.home_about_area')
    @include('frontend.home.home_service_area');
    @include('frontend.home.home_work_process_area');
    @include('frontend.home.home_portfolio_area');
    @include('frontend.home.home_partner_area');
    @include('frontend.home.home_testimonial_area');
    @include('frontend.home.home_blog_area')
    @include('frontend.home.home_contact_area');
@endsection
